// Code generated by ent, DO NOT EDIT.

package tenantconfig

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the tenantconfig type in the database.
	Label = "tenant_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenant holds the string denoting the tenant field in the database.
	FieldTenant = "tenant"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the tenantconfig in the database.
	Table = "tenant_configs"
)

// Columns holds all SQL columns for tenantconfig fields.
var Columns = []string{
	FieldID,
	FieldTenant,
	FieldPayload,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the TenantConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenant orders the results by the tenant field.
func ByTenant(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenant, opts...).ToFunc()
}

// ByPayload orders the results by the payload field.
func ByPayload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayload, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
