// Code generated by ent, DO NOT EDIT.

package tenantconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/ca-x/nowledge-mem-snap/internal/persist/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldLTE(FieldID, id))
}

// Tenant applies equality check predicate on the "tenant" field. It's identical to TenantEQ.
func Tenant(v string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldEQ(FieldTenant, v))
}

// Payload applies equality check predicate on the "payload" field. It's identical to PayloadEQ.
func Payload(v string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldEQ(FieldPayload, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantEQ applies the EQ predicate on the "tenant" field.
func TenantEQ(v string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldEQ(FieldTenant, v))
}

// TenantNEQ applies the NEQ predicate on the "tenant" field.
func TenantNEQ(v string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldNEQ(FieldTenant, v))
}

// TenantIn applies the In predicate on the "tenant" field.
func TenantIn(vs ...string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldIn(FieldTenant, vs...))
}

// TenantNotIn applies the NotIn predicate on the "tenant" field.
func TenantNotIn(vs ...string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldNotIn(FieldTenant, vs...))
}

// TenantGT applies the GT predicate on the "tenant" field.
func TenantGT(v string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldGT(FieldTenant, v))
}

// TenantGTE applies the GTE predicate on the "tenant" field.
func TenantGTE(v string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldGTE(FieldTenant, v))
}

// TenantLT applies the LT predicate on the "tenant" field.
func TenantLT(v string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldLT(FieldTenant, v))
}

// TenantLTE applies the LTE predicate on the "tenant" field.
func TenantLTE(v string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldLTE(FieldTenant, v))
}

// TenantContains applies the Contains predicate on the "tenant" field.
func TenantContains(v string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldContains(FieldTenant, v))
}

// TenantHasPrefix applies the HasPrefix predicate on the "tenant" field.
func TenantHasPrefix(v string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldHasPrefix(FieldTenant, v))
}

// TenantHasSuffix applies the HasSuffix predicate on the "tenant" field.
func TenantHasSuffix(v string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldHasSuffix(FieldTenant, v))
}

// TenantEqualFold applies the EqualFold predicate on the "tenant" field.
func TenantEqualFold(v string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldEqualFold(FieldTenant, v))
}

// TenantContainsFold applies the ContainsFold predicate on the "tenant" field.
func TenantContainsFold(v string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldContainsFold(FieldTenant, v))
}

// PayloadEQ applies the EQ predicate on the "payload" field.
func PayloadEQ(v string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldEQ(FieldPayload, v))
}

// PayloadNEQ applies the NEQ predicate on the "payload" field.
func PayloadNEQ(v string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldNEQ(FieldPayload, v))
}

// PayloadIn applies the In predicate on the "payload" field.
func PayloadIn(vs ...string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldIn(FieldPayload, vs...))
}

// PayloadNotIn applies the NotIn predicate on the "payload" field.
func PayloadNotIn(vs ...string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldNotIn(FieldPayload, vs...))
}

// PayloadGT applies the GT predicate on the "payload" field.
func PayloadGT(v string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldGT(FieldPayload, v))
}

// PayloadGTE applies the GTE predicate on the "payload" field.
func PayloadGTE(v string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldGTE(FieldPayload, v))
}

// PayloadLT applies the LT predicate on the "payload" field.
func PayloadLT(v string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldLT(FieldPayload, v))
}

// PayloadLTE applies the LTE predicate on the "payload" field.
func PayloadLTE(v string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldLTE(FieldPayload, v))
}

// PayloadContains applies the Contains predicate on the "payload" field.
func PayloadContains(v string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldContains(FieldPayload, v))
}

// PayloadHasPrefix applies the HasPrefix predicate on the "payload" field.
func PayloadHasPrefix(v string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldHasPrefix(FieldPayload, v))
}

// PayloadHasSuffix applies the HasSuffix predicate on the "payload" field.
func PayloadHasSuffix(v string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldHasSuffix(FieldPayload, v))
}

// PayloadEqualFold applies the EqualFold predicate on the "payload" field.
func PayloadEqualFold(v string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldEqualFold(FieldPayload, v))
}

// PayloadContainsFold applies the ContainsFold predicate on the "payload" field.
func PayloadContainsFold(v string) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldContainsFold(FieldPayload, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TenantConfig {
	return predicate.TenantConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TenantConfig) predicate.TenantConfig {
	return predicate.TenantConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TenantConfig) predicate.TenantConfig {
	return predicate.TenantConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TenantConfig) predicate.TenantConfig {
	return predicate.TenantConfig(sql.NotPredicates(p))
}
