// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// RunRecord is the predicate function for runrecord builders.
type RunRecord func(*sql.Selector)

// SystemConfig is the predicate function for systemconfig builders.
type SystemConfig func(*sql.Selector)

// TenantConfig is the predicate function for tenantconfig builders.
type TenantConfig func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
