// Code generated by ent, DO NOT EDIT.

package runrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/lib-x/nowledge-mem-snap/internal/persist/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldLTE(FieldID, id))
}

// Tenant applies equality check predicate on the "tenant" field. It's identical to TenantEQ.
func Tenant(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldEQ(FieldTenant, v))
}

// RunID applies equality check predicate on the "run_id" field. It's identical to RunIDEQ.
func RunID(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldEQ(FieldRunID, v))
}

// Payload applies equality check predicate on the "payload" field. It's identical to PayloadEQ.
func Payload(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldEQ(FieldPayload, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldEQ(FieldStartedAt, v))
}

// TenantEQ applies the EQ predicate on the "tenant" field.
func TenantEQ(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldEQ(FieldTenant, v))
}

// TenantNEQ applies the NEQ predicate on the "tenant" field.
func TenantNEQ(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldNEQ(FieldTenant, v))
}

// TenantIn applies the In predicate on the "tenant" field.
func TenantIn(vs ...string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldIn(FieldTenant, vs...))
}

// TenantNotIn applies the NotIn predicate on the "tenant" field.
func TenantNotIn(vs ...string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldNotIn(FieldTenant, vs...))
}

// TenantGT applies the GT predicate on the "tenant" field.
func TenantGT(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldGT(FieldTenant, v))
}

// TenantGTE applies the GTE predicate on the "tenant" field.
func TenantGTE(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldGTE(FieldTenant, v))
}

// TenantLT applies the LT predicate on the "tenant" field.
func TenantLT(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldLT(FieldTenant, v))
}

// TenantLTE applies the LTE predicate on the "tenant" field.
func TenantLTE(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldLTE(FieldTenant, v))
}

// TenantContains applies the Contains predicate on the "tenant" field.
func TenantContains(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldContains(FieldTenant, v))
}

// TenantHasPrefix applies the HasPrefix predicate on the "tenant" field.
func TenantHasPrefix(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldHasPrefix(FieldTenant, v))
}

// TenantHasSuffix applies the HasSuffix predicate on the "tenant" field.
func TenantHasSuffix(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldHasSuffix(FieldTenant, v))
}

// TenantEqualFold applies the EqualFold predicate on the "tenant" field.
func TenantEqualFold(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldEqualFold(FieldTenant, v))
}

// TenantContainsFold applies the ContainsFold predicate on the "tenant" field.
func TenantContainsFold(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldContainsFold(FieldTenant, v))
}

// RunIDEQ applies the EQ predicate on the "run_id" field.
func RunIDEQ(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldEQ(FieldRunID, v))
}

// RunIDNEQ applies the NEQ predicate on the "run_id" field.
func RunIDNEQ(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldNEQ(FieldRunID, v))
}

// RunIDIn applies the In predicate on the "run_id" field.
func RunIDIn(vs ...string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldIn(FieldRunID, vs...))
}

// RunIDNotIn applies the NotIn predicate on the "run_id" field.
func RunIDNotIn(vs ...string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldNotIn(FieldRunID, vs...))
}

// RunIDGT applies the GT predicate on the "run_id" field.
func RunIDGT(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldGT(FieldRunID, v))
}

// RunIDGTE applies the GTE predicate on the "run_id" field.
func RunIDGTE(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldGTE(FieldRunID, v))
}

// RunIDLT applies the LT predicate on the "run_id" field.
func RunIDLT(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldLT(FieldRunID, v))
}

// RunIDLTE applies the LTE predicate on the "run_id" field.
func RunIDLTE(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldLTE(FieldRunID, v))
}

// RunIDContains applies the Contains predicate on the "run_id" field.
func RunIDContains(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldContains(FieldRunID, v))
}

// RunIDHasPrefix applies the HasPrefix predicate on the "run_id" field.
func RunIDHasPrefix(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldHasPrefix(FieldRunID, v))
}

// RunIDHasSuffix applies the HasSuffix predicate on the "run_id" field.
func RunIDHasSuffix(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldHasSuffix(FieldRunID, v))
}

// RunIDEqualFold applies the EqualFold predicate on the "run_id" field.
func RunIDEqualFold(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldEqualFold(FieldRunID, v))
}

// RunIDContainsFold applies the ContainsFold predicate on the "run_id" field.
func RunIDContainsFold(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldContainsFold(FieldRunID, v))
}

// PayloadEQ applies the EQ predicate on the "payload" field.
func PayloadEQ(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldEQ(FieldPayload, v))
}

// PayloadNEQ applies the NEQ predicate on the "payload" field.
func PayloadNEQ(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldNEQ(FieldPayload, v))
}

// PayloadIn applies the In predicate on the "payload" field.
func PayloadIn(vs ...string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldIn(FieldPayload, vs...))
}

// PayloadNotIn applies the NotIn predicate on the "payload" field.
func PayloadNotIn(vs ...string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldNotIn(FieldPayload, vs...))
}

// PayloadGT applies the GT predicate on the "payload" field.
func PayloadGT(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldGT(FieldPayload, v))
}

// PayloadGTE applies the GTE predicate on the "payload" field.
func PayloadGTE(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldGTE(FieldPayload, v))
}

// PayloadLT applies the LT predicate on the "payload" field.
func PayloadLT(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldLT(FieldPayload, v))
}

// PayloadLTE applies the LTE predicate on the "payload" field.
func PayloadLTE(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldLTE(FieldPayload, v))
}

// PayloadContains applies the Contains predicate on the "payload" field.
func PayloadContains(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldContains(FieldPayload, v))
}

// PayloadHasPrefix applies the HasPrefix predicate on the "payload" field.
func PayloadHasPrefix(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldHasPrefix(FieldPayload, v))
}

// PayloadHasSuffix applies the HasSuffix predicate on the "payload" field.
func PayloadHasSuffix(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldHasSuffix(FieldPayload, v))
}

// PayloadEqualFold applies the EqualFold predicate on the "payload" field.
func PayloadEqualFold(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldEqualFold(FieldPayload, v))
}

// PayloadContainsFold applies the ContainsFold predicate on the "payload" field.
func PayloadContainsFold(v string) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldContainsFold(FieldPayload, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.RunRecord {
	return predicate.RunRecord(sql.FieldLTE(FieldStartedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RunRecord) predicate.RunRecord {
	return predicate.RunRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RunRecord) predicate.RunRecord {
	return predicate.RunRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RunRecord) predicate.RunRecord {
	return predicate.RunRecord(sql.NotPredicates(p))
}
