// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/ca-x/nowledge-mem-snap/internal/persist/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// Tenant applies equality check predicate on the "tenant" field. It's identical to TenantEQ.
func Tenant(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTenant, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUsername, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// PasswordHash applies equality check predicate on the "password_hash" field. It's identical to PasswordHashEQ.
func PasswordHash(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPasswordHash, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldDisplayName, v))
}

// AvatarURL applies equality check predicate on the "avatar_url" field. It's identical to AvatarURLEQ.
func AvatarURL(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatarURL, v))
}

// OidcIssuer applies equality check predicate on the "oidc_issuer" field. It's identical to OidcIssuerEQ.
func OidcIssuer(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldOidcIssuer, v))
}

// OidcSubject applies equality check predicate on the "oidc_subject" field. It's identical to OidcSubjectEQ.
func OidcSubject(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldOidcSubject, v))
}

// OidcEmail applies equality check predicate on the "oidc_email" field. It's identical to OidcEmailEQ.
func OidcEmail(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldOidcEmail, v))
}

// IsAdmin applies equality check predicate on the "is_admin" field. It's identical to IsAdminEQ.
func IsAdmin(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsAdmin, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// TenantEQ applies the EQ predicate on the "tenant" field.
func TenantEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTenant, v))
}

// TenantNEQ applies the NEQ predicate on the "tenant" field.
func TenantNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldTenant, v))
}

// TenantIn applies the In predicate on the "tenant" field.
func TenantIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldTenant, vs...))
}

// TenantNotIn applies the NotIn predicate on the "tenant" field.
func TenantNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldTenant, vs...))
}

// TenantGT applies the GT predicate on the "tenant" field.
func TenantGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldTenant, v))
}

// TenantGTE applies the GTE predicate on the "tenant" field.
func TenantGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldTenant, v))
}

// TenantLT applies the LT predicate on the "tenant" field.
func TenantLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldTenant, v))
}

// TenantLTE applies the LTE predicate on the "tenant" field.
func TenantLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldTenant, v))
}

// TenantContains applies the Contains predicate on the "tenant" field.
func TenantContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldTenant, v))
}

// TenantHasPrefix applies the HasPrefix predicate on the "tenant" field.
func TenantHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldTenant, v))
}

// TenantHasSuffix applies the HasSuffix predicate on the "tenant" field.
func TenantHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldTenant, v))
}

// TenantEqualFold applies the EqualFold predicate on the "tenant" field.
func TenantEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldTenant, v))
}

// TenantContainsFold applies the ContainsFold predicate on the "tenant" field.
func TenantContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldTenant, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldUsername, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldEmail, v))
}

// PasswordHashEQ applies the EQ predicate on the "password_hash" field.
func PasswordHashEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPasswordHash, v))
}

// PasswordHashNEQ applies the NEQ predicate on the "password_hash" field.
func PasswordHashNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPasswordHash, v))
}

// PasswordHashIn applies the In predicate on the "password_hash" field.
func PasswordHashIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldPasswordHash, vs...))
}

// PasswordHashNotIn applies the NotIn predicate on the "password_hash" field.
func PasswordHashNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPasswordHash, vs...))
}

// PasswordHashGT applies the GT predicate on the "password_hash" field.
func PasswordHashGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldPasswordHash, v))
}

// PasswordHashGTE applies the GTE predicate on the "password_hash" field.
func PasswordHashGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPasswordHash, v))
}

// PasswordHashLT applies the LT predicate on the "password_hash" field.
func PasswordHashLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldPasswordHash, v))
}

// PasswordHashLTE applies the LTE predicate on the "password_hash" field.
func PasswordHashLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPasswordHash, v))
}

// PasswordHashContains applies the Contains predicate on the "password_hash" field.
func PasswordHashContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldPasswordHash, v))
}

// PasswordHashHasPrefix applies the HasPrefix predicate on the "password_hash" field.
func PasswordHashHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldPasswordHash, v))
}

// PasswordHashHasSuffix applies the HasSuffix predicate on the "password_hash" field.
func PasswordHashHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldPasswordHash, v))
}

// PasswordHashEqualFold applies the EqualFold predicate on the "password_hash" field.
func PasswordHashEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldPasswordHash, v))
}

// PasswordHashContainsFold applies the ContainsFold predicate on the "password_hash" field.
func PasswordHashContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldPasswordHash, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameIsNil applies the IsNil predicate on the "display_name" field.
func DisplayNameIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldDisplayName))
}

// DisplayNameNotNil applies the NotNil predicate on the "display_name" field.
func DisplayNameNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldDisplayName))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldDisplayName, v))
}

// AvatarURLEQ applies the EQ predicate on the "avatar_url" field.
func AvatarURLEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatarURL, v))
}

// AvatarURLNEQ applies the NEQ predicate on the "avatar_url" field.
func AvatarURLNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAvatarURL, v))
}

// AvatarURLIn applies the In predicate on the "avatar_url" field.
func AvatarURLIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAvatarURL, vs...))
}

// AvatarURLNotIn applies the NotIn predicate on the "avatar_url" field.
func AvatarURLNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAvatarURL, vs...))
}

// AvatarURLGT applies the GT predicate on the "avatar_url" field.
func AvatarURLGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAvatarURL, v))
}

// AvatarURLGTE applies the GTE predicate on the "avatar_url" field.
func AvatarURLGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAvatarURL, v))
}

// AvatarURLLT applies the LT predicate on the "avatar_url" field.
func AvatarURLLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAvatarURL, v))
}

// AvatarURLLTE applies the LTE predicate on the "avatar_url" field.
func AvatarURLLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAvatarURL, v))
}

// AvatarURLContains applies the Contains predicate on the "avatar_url" field.
func AvatarURLContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAvatarURL, v))
}

// AvatarURLHasPrefix applies the HasPrefix predicate on the "avatar_url" field.
func AvatarURLHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAvatarURL, v))
}

// AvatarURLHasSuffix applies the HasSuffix predicate on the "avatar_url" field.
func AvatarURLHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAvatarURL, v))
}

// AvatarURLIsNil applies the IsNil predicate on the "avatar_url" field.
func AvatarURLIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldAvatarURL))
}

// AvatarURLNotNil applies the NotNil predicate on the "avatar_url" field.
func AvatarURLNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldAvatarURL))
}

// AvatarURLEqualFold applies the EqualFold predicate on the "avatar_url" field.
func AvatarURLEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAvatarURL, v))
}

// AvatarURLContainsFold applies the ContainsFold predicate on the "avatar_url" field.
func AvatarURLContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAvatarURL, v))
}

// OidcIssuerEQ applies the EQ predicate on the "oidc_issuer" field.
func OidcIssuerEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldOidcIssuer, v))
}

// OidcIssuerNEQ applies the NEQ predicate on the "oidc_issuer" field.
func OidcIssuerNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldOidcIssuer, v))
}

// OidcIssuerIn applies the In predicate on the "oidc_issuer" field.
func OidcIssuerIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldOidcIssuer, vs...))
}

// OidcIssuerNotIn applies the NotIn predicate on the "oidc_issuer" field.
func OidcIssuerNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldOidcIssuer, vs...))
}

// OidcIssuerGT applies the GT predicate on the "oidc_issuer" field.
func OidcIssuerGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldOidcIssuer, v))
}

// OidcIssuerGTE applies the GTE predicate on the "oidc_issuer" field.
func OidcIssuerGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldOidcIssuer, v))
}

// OidcIssuerLT applies the LT predicate on the "oidc_issuer" field.
func OidcIssuerLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldOidcIssuer, v))
}

// OidcIssuerLTE applies the LTE predicate on the "oidc_issuer" field.
func OidcIssuerLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldOidcIssuer, v))
}

// OidcIssuerContains applies the Contains predicate on the "oidc_issuer" field.
func OidcIssuerContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldOidcIssuer, v))
}

// OidcIssuerHasPrefix applies the HasPrefix predicate on the "oidc_issuer" field.
func OidcIssuerHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldOidcIssuer, v))
}

// OidcIssuerHasSuffix applies the HasSuffix predicate on the "oidc_issuer" field.
func OidcIssuerHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldOidcIssuer, v))
}

// OidcIssuerIsNil applies the IsNil predicate on the "oidc_issuer" field.
func OidcIssuerIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldOidcIssuer))
}

// OidcIssuerNotNil applies the NotNil predicate on the "oidc_issuer" field.
func OidcIssuerNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldOidcIssuer))
}

// OidcIssuerEqualFold applies the EqualFold predicate on the "oidc_issuer" field.
func OidcIssuerEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldOidcIssuer, v))
}

// OidcIssuerContainsFold applies the ContainsFold predicate on the "oidc_issuer" field.
func OidcIssuerContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldOidcIssuer, v))
}

// OidcSubjectEQ applies the EQ predicate on the "oidc_subject" field.
func OidcSubjectEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldOidcSubject, v))
}

// OidcSubjectNEQ applies the NEQ predicate on the "oidc_subject" field.
func OidcSubjectNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldOidcSubject, v))
}

// OidcSubjectIn applies the In predicate on the "oidc_subject" field.
func OidcSubjectIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldOidcSubject, vs...))
}

// OidcSubjectNotIn applies the NotIn predicate on the "oidc_subject" field.
func OidcSubjectNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldOidcSubject, vs...))
}

// OidcSubjectGT applies the GT predicate on the "oidc_subject" field.
func OidcSubjectGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldOidcSubject, v))
}

// OidcSubjectGTE applies the GTE predicate on the "oidc_subject" field.
func OidcSubjectGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldOidcSubject, v))
}

// OidcSubjectLT applies the LT predicate on the "oidc_subject" field.
func OidcSubjectLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldOidcSubject, v))
}

// OidcSubjectLTE applies the LTE predicate on the "oidc_subject" field.
func OidcSubjectLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldOidcSubject, v))
}

// OidcSubjectContains applies the Contains predicate on the "oidc_subject" field.
func OidcSubjectContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldOidcSubject, v))
}

// OidcSubjectHasPrefix applies the HasPrefix predicate on the "oidc_subject" field.
func OidcSubjectHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldOidcSubject, v))
}

// OidcSubjectHasSuffix applies the HasSuffix predicate on the "oidc_subject" field.
func OidcSubjectHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldOidcSubject, v))
}

// OidcSubjectIsNil applies the IsNil predicate on the "oidc_subject" field.
func OidcSubjectIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldOidcSubject))
}

// OidcSubjectNotNil applies the NotNil predicate on the "oidc_subject" field.
func OidcSubjectNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldOidcSubject))
}

// OidcSubjectEqualFold applies the EqualFold predicate on the "oidc_subject" field.
func OidcSubjectEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldOidcSubject, v))
}

// OidcSubjectContainsFold applies the ContainsFold predicate on the "oidc_subject" field.
func OidcSubjectContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldOidcSubject, v))
}

// OidcEmailEQ applies the EQ predicate on the "oidc_email" field.
func OidcEmailEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldOidcEmail, v))
}

// OidcEmailNEQ applies the NEQ predicate on the "oidc_email" field.
func OidcEmailNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldOidcEmail, v))
}

// OidcEmailIn applies the In predicate on the "oidc_email" field.
func OidcEmailIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldOidcEmail, vs...))
}

// OidcEmailNotIn applies the NotIn predicate on the "oidc_email" field.
func OidcEmailNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldOidcEmail, vs...))
}

// OidcEmailGT applies the GT predicate on the "oidc_email" field.
func OidcEmailGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldOidcEmail, v))
}

// OidcEmailGTE applies the GTE predicate on the "oidc_email" field.
func OidcEmailGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldOidcEmail, v))
}

// OidcEmailLT applies the LT predicate on the "oidc_email" field.
func OidcEmailLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldOidcEmail, v))
}

// OidcEmailLTE applies the LTE predicate on the "oidc_email" field.
func OidcEmailLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldOidcEmail, v))
}

// OidcEmailContains applies the Contains predicate on the "oidc_email" field.
func OidcEmailContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldOidcEmail, v))
}

// OidcEmailHasPrefix applies the HasPrefix predicate on the "oidc_email" field.
func OidcEmailHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldOidcEmail, v))
}

// OidcEmailHasSuffix applies the HasSuffix predicate on the "oidc_email" field.
func OidcEmailHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldOidcEmail, v))
}

// OidcEmailIsNil applies the IsNil predicate on the "oidc_email" field.
func OidcEmailIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldOidcEmail))
}

// OidcEmailNotNil applies the NotNil predicate on the "oidc_email" field.
func OidcEmailNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldOidcEmail))
}

// OidcEmailEqualFold applies the EqualFold predicate on the "oidc_email" field.
func OidcEmailEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldOidcEmail, v))
}

// OidcEmailContainsFold applies the ContainsFold predicate on the "oidc_email" field.
func OidcEmailContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldOidcEmail, v))
}

// IsAdminEQ applies the EQ predicate on the "is_admin" field.
func IsAdminEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsAdmin, v))
}

// IsAdminNEQ applies the NEQ predicate on the "is_admin" field.
func IsAdminNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldIsAdmin, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
