// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RunRecordsColumns holds the columns for the "run_records" table.
	RunRecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "tenant", Type: field.TypeString},
		{Name: "run_id", Type: field.TypeString},
		{Name: "payload", Type: field.TypeString},
		{Name: "started_at", Type: field.TypeTime},
	}
	// RunRecordsTable holds the schema information for the "run_records" table.
	RunRecordsTable = &schema.Table{
		Name:       "run_records",
		Columns:    RunRecordsColumns,
		PrimaryKey: []*schema.Column{RunRecordsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "runrecord_tenant_run_id",
				Unique:  true,
				Columns: []*schema.Column{RunRecordsColumns[1], RunRecordsColumns[2]},
			},
			{
				Name:    "runrecord_tenant_started_at",
				Unique:  false,
				Columns: []*schema.Column{RunRecordsColumns[1], RunRecordsColumns[4]},
			},
		},
	}
	// SystemConfigsColumns holds the columns for the "system_configs" table.
	SystemConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "payload", Type: field.TypeString},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SystemConfigsTable holds the schema information for the "system_configs" table.
	SystemConfigsTable = &schema.Table{
		Name:       "system_configs",
		Columns:    SystemConfigsColumns,
		PrimaryKey: []*schema.Column{SystemConfigsColumns[0]},
	}
	// TenantConfigsColumns holds the columns for the "tenant_configs" table.
	TenantConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "tenant", Type: field.TypeString, Unique: true},
		{Name: "payload", Type: field.TypeString},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TenantConfigsTable holds the schema information for the "tenant_configs" table.
	TenantConfigsTable = &schema.Table{
		Name:       "tenant_configs",
		Columns:    TenantConfigsColumns,
		PrimaryKey: []*schema.Column{TenantConfigsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "tenant", Type: field.TypeString},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "display_name", Type: field.TypeString, Nullable: true},
		{Name: "avatar_url", Type: field.TypeString, Nullable: true},
		{Name: "is_admin", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_tenant",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RunRecordsTable,
		SystemConfigsTable,
		TenantConfigsTable,
		UsersTable,
	}
)

func init() {
}
