// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lib-x/nowledge-mem-snap/internal/persist/ent/runrecord"
)

// RunRecord is the model entity for the RunRecord schema.
type RunRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Tenant holds the value of the "tenant" field.
	Tenant string `json:"tenant,omitempty"`
	// RunID holds the value of the "run_id" field.
	RunID string `json:"run_id,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload string `json:"payload,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt    time.Time `json:"started_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RunRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case runrecord.FieldID:
			values[i] = new(sql.NullInt64)
		case runrecord.FieldTenant, runrecord.FieldRunID, runrecord.FieldPayload:
			values[i] = new(sql.NullString)
		case runrecord.FieldStartedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RunRecord fields.
func (_m *RunRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case runrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case runrecord.FieldTenant:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant", values[i])
			} else if value.Valid {
				_m.Tenant = value.String
			}
		case runrecord.FieldRunID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field run_id", values[i])
			} else if value.Valid {
				_m.RunID = value.String
			}
		case runrecord.FieldPayload:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value.Valid {
				_m.Payload = value.String
			}
		case runrecord.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RunRecord.
// This includes values selected through modifiers, order, etc.
func (_m *RunRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RunRecord.
// Note that you need to call RunRecord.Unwrap() before calling this method if this RunRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RunRecord) Update() *RunRecordUpdateOne {
	return NewRunRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RunRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RunRecord) Unwrap() *RunRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RunRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RunRecord) String() string {
	var builder strings.Builder
	builder.WriteString("RunRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant=")
	builder.WriteString(_m.Tenant)
	builder.WriteString(", ")
	builder.WriteString("run_id=")
	builder.WriteString(_m.RunID)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(_m.Payload)
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RunRecords is a parsable slice of RunRecord.
type RunRecords []*RunRecord
