// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lib-x/nowledge-mem-snap/internal/persist/ent/predicate"
	"github.com/lib-x/nowledge-mem-snap/internal/persist/ent/runrecord"
)

// RunRecordUpdate is the builder for updating RunRecord entities.
type RunRecordUpdate struct {
	config
	hooks    []Hook
	mutation *RunRecordMutation
}

// Where appends a list predicates to the RunRecordUpdate builder.
func (_u *RunRecordUpdate) Where(ps ...predicate.RunRecord) *RunRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenant sets the "tenant" field.
func (_u *RunRecordUpdate) SetTenant(v string) *RunRecordUpdate {
	_u.mutation.SetTenant(v)
	return _u
}

// SetNillableTenant sets the "tenant" field if the given value is not nil.
func (_u *RunRecordUpdate) SetNillableTenant(v *string) *RunRecordUpdate {
	if v != nil {
		_u.SetTenant(*v)
	}
	return _u
}

// SetRunID sets the "run_id" field.
func (_u *RunRecordUpdate) SetRunID(v string) *RunRecordUpdate {
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *RunRecordUpdate) SetNillableRunID(v *string) *RunRecordUpdate {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *RunRecordUpdate) SetPayload(v string) *RunRecordUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *RunRecordUpdate) SetNillablePayload(v *string) *RunRecordUpdate {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *RunRecordUpdate) SetStartedAt(v time.Time) *RunRecordUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *RunRecordUpdate) SetNillableStartedAt(v *time.Time) *RunRecordUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// Mutation returns the RunRecordMutation object of the builder.
func (_u *RunRecordUpdate) Mutation() *RunRecordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RunRecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RunRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RunRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RunRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RunRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(runrecord.Table, runrecord.Columns, sqlgraph.NewFieldSpec(runrecord.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Tenant(); ok {
		_spec.SetField(runrecord.FieldTenant, field.TypeString, value)
	}
	if value, ok := _u.mutation.RunID(); ok {
		_spec.SetField(runrecord.FieldRunID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(runrecord.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(runrecord.FieldStartedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{runrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RunRecordUpdateOne is the builder for updating a single RunRecord entity.
type RunRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RunRecordMutation
}

// SetTenant sets the "tenant" field.
func (_u *RunRecordUpdateOne) SetTenant(v string) *RunRecordUpdateOne {
	_u.mutation.SetTenant(v)
	return _u
}

// SetNillableTenant sets the "tenant" field if the given value is not nil.
func (_u *RunRecordUpdateOne) SetNillableTenant(v *string) *RunRecordUpdateOne {
	if v != nil {
		_u.SetTenant(*v)
	}
	return _u
}

// SetRunID sets the "run_id" field.
func (_u *RunRecordUpdateOne) SetRunID(v string) *RunRecordUpdateOne {
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *RunRecordUpdateOne) SetNillableRunID(v *string) *RunRecordUpdateOne {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *RunRecordUpdateOne) SetPayload(v string) *RunRecordUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *RunRecordUpdateOne) SetNillablePayload(v *string) *RunRecordUpdateOne {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *RunRecordUpdateOne) SetStartedAt(v time.Time) *RunRecordUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *RunRecordUpdateOne) SetNillableStartedAt(v *time.Time) *RunRecordUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// Mutation returns the RunRecordMutation object of the builder.
func (_u *RunRecordUpdateOne) Mutation() *RunRecordMutation {
	return _u.mutation
}

// Where appends a list predicates to the RunRecordUpdate builder.
func (_u *RunRecordUpdateOne) Where(ps ...predicate.RunRecord) *RunRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RunRecordUpdateOne) Select(field string, fields ...string) *RunRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RunRecord entity.
func (_u *RunRecordUpdateOne) Save(ctx context.Context) (*RunRecord, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RunRecordUpdateOne) SaveX(ctx context.Context) *RunRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RunRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RunRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RunRecordUpdateOne) sqlSave(ctx context.Context) (_node *RunRecord, err error) {
	_spec := sqlgraph.NewUpdateSpec(runrecord.Table, runrecord.Columns, sqlgraph.NewFieldSpec(runrecord.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RunRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, runrecord.FieldID)
		for _, f := range fields {
			if !runrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != runrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Tenant(); ok {
		_spec.SetField(runrecord.FieldTenant, field.TypeString, value)
	}
	if value, ok := _u.mutation.RunID(); ok {
		_spec.SetField(runrecord.FieldRunID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(runrecord.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(runrecord.FieldStartedAt, field.TypeTime, value)
	}
	_node = &RunRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{runrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
