// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lib-x/nowledge-mem-snap/internal/persist/ent/runrecord"
)

// RunRecordCreate is the builder for creating a RunRecord entity.
type RunRecordCreate struct {
	config
	mutation *RunRecordMutation
	hooks    []Hook
}

// SetTenant sets the "tenant" field.
func (_c *RunRecordCreate) SetTenant(v string) *RunRecordCreate {
	_c.mutation.SetTenant(v)
	return _c
}

// SetRunID sets the "run_id" field.
func (_c *RunRecordCreate) SetRunID(v string) *RunRecordCreate {
	_c.mutation.SetRunID(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *RunRecordCreate) SetPayload(v string) *RunRecordCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *RunRecordCreate) SetStartedAt(v time.Time) *RunRecordCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// Mutation returns the RunRecordMutation object of the builder.
func (_c *RunRecordCreate) Mutation() *RunRecordMutation {
	return _c.mutation
}

// Save creates the RunRecord in the database.
func (_c *RunRecordCreate) Save(ctx context.Context) (*RunRecord, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RunRecordCreate) SaveX(ctx context.Context) *RunRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RunRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RunRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RunRecordCreate) check() error {
	if _, ok := _c.mutation.Tenant(); !ok {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required field "RunRecord.tenant"`)}
	}
	if _, ok := _c.mutation.RunID(); !ok {
		return &ValidationError{Name: "run_id", err: errors.New(`ent: missing required field "RunRecord.run_id"`)}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "RunRecord.payload"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "RunRecord.started_at"`)}
	}
	return nil
}

func (_c *RunRecordCreate) sqlSave(ctx context.Context) (*RunRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RunRecordCreate) createSpec() (*RunRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &RunRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(runrecord.Table, sqlgraph.NewFieldSpec(runrecord.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Tenant(); ok {
		_spec.SetField(runrecord.FieldTenant, field.TypeString, value)
		_node.Tenant = value
	}
	if value, ok := _c.mutation.RunID(); ok {
		_spec.SetField(runrecord.FieldRunID, field.TypeString, value)
		_node.RunID = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(runrecord.FieldPayload, field.TypeString, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(runrecord.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	return _node, _spec
}

// RunRecordCreateBulk is the builder for creating many RunRecord entities in bulk.
type RunRecordCreateBulk struct {
	config
	err      error
	builders []*RunRecordCreate
}

// Save creates the RunRecord entities in the database.
func (_c *RunRecordCreateBulk) Save(ctx context.Context) ([]*RunRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RunRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RunRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RunRecordCreateBulk) SaveX(ctx context.Context) []*RunRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RunRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RunRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
