// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lib-x/nowledge-mem-snap/internal/persist/ent/tenantconfig"
)

// TenantConfigCreate is the builder for creating a TenantConfig entity.
type TenantConfigCreate struct {
	config
	mutation *TenantConfigMutation
	hooks    []Hook
}

// SetTenant sets the "tenant" field.
func (_c *TenantConfigCreate) SetTenant(v string) *TenantConfigCreate {
	_c.mutation.SetTenant(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *TenantConfigCreate) SetPayload(v string) *TenantConfigCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TenantConfigCreate) SetUpdatedAt(v time.Time) *TenantConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// Mutation returns the TenantConfigMutation object of the builder.
func (_c *TenantConfigCreate) Mutation() *TenantConfigMutation {
	return _c.mutation
}

// Save creates the TenantConfig in the database.
func (_c *TenantConfigCreate) Save(ctx context.Context) (*TenantConfig, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TenantConfigCreate) SaveX(ctx context.Context) *TenantConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TenantConfigCreate) check() error {
	if _, ok := _c.mutation.Tenant(); !ok {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required field "TenantConfig.tenant"`)}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "TenantConfig.payload"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TenantConfig.updated_at"`)}
	}
	return nil
}

func (_c *TenantConfigCreate) sqlSave(ctx context.Context) (*TenantConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TenantConfigCreate) createSpec() (*TenantConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &TenantConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tenantconfig.Table, sqlgraph.NewFieldSpec(tenantconfig.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Tenant(); ok {
		_spec.SetField(tenantconfig.FieldTenant, field.TypeString, value)
		_node.Tenant = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(tenantconfig.FieldPayload, field.TypeString, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// TenantConfigCreateBulk is the builder for creating many TenantConfig entities in bulk.
type TenantConfigCreateBulk struct {
	config
	err      error
	builders []*TenantConfigCreate
}

// Save creates the TenantConfig entities in the database.
func (_c *TenantConfigCreateBulk) Save(ctx context.Context) ([]*TenantConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TenantConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TenantConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TenantConfigCreateBulk) SaveX(ctx context.Context) []*TenantConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
