// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lib-x/nowledge-mem-snap/internal/persist/ent/predicate"
	"github.com/lib-x/nowledge-mem-snap/internal/persist/ent/tenantconfig"
)

// TenantConfigUpdate is the builder for updating TenantConfig entities.
type TenantConfigUpdate struct {
	config
	hooks    []Hook
	mutation *TenantConfigMutation
}

// Where appends a list predicates to the TenantConfigUpdate builder.
func (_u *TenantConfigUpdate) Where(ps ...predicate.TenantConfig) *TenantConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenant sets the "tenant" field.
func (_u *TenantConfigUpdate) SetTenant(v string) *TenantConfigUpdate {
	_u.mutation.SetTenant(v)
	return _u
}

// SetNillableTenant sets the "tenant" field if the given value is not nil.
func (_u *TenantConfigUpdate) SetNillableTenant(v *string) *TenantConfigUpdate {
	if v != nil {
		_u.SetTenant(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *TenantConfigUpdate) SetPayload(v string) *TenantConfigUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *TenantConfigUpdate) SetNillablePayload(v *string) *TenantConfigUpdate {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantConfigUpdate) SetUpdatedAt(v time.Time) *TenantConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *TenantConfigUpdate) SetNillableUpdatedAt(v *time.Time) *TenantConfigUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the TenantConfigMutation object of the builder.
func (_u *TenantConfigUpdate) Mutation() *TenantConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantConfigUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TenantConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(tenantconfig.Table, tenantconfig.Columns, sqlgraph.NewFieldSpec(tenantconfig.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Tenant(); ok {
		_spec.SetField(tenantconfig.FieldTenant, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(tenantconfig.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantConfigUpdateOne is the builder for updating a single TenantConfig entity.
type TenantConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantConfigMutation
}

// SetTenant sets the "tenant" field.
func (_u *TenantConfigUpdateOne) SetTenant(v string) *TenantConfigUpdateOne {
	_u.mutation.SetTenant(v)
	return _u
}

// SetNillableTenant sets the "tenant" field if the given value is not nil.
func (_u *TenantConfigUpdateOne) SetNillableTenant(v *string) *TenantConfigUpdateOne {
	if v != nil {
		_u.SetTenant(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *TenantConfigUpdateOne) SetPayload(v string) *TenantConfigUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *TenantConfigUpdateOne) SetNillablePayload(v *string) *TenantConfigUpdateOne {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantConfigUpdateOne) SetUpdatedAt(v time.Time) *TenantConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *TenantConfigUpdateOne) SetNillableUpdatedAt(v *time.Time) *TenantConfigUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the TenantConfigMutation object of the builder.
func (_u *TenantConfigUpdateOne) Mutation() *TenantConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the TenantConfigUpdate builder.
func (_u *TenantConfigUpdateOne) Where(ps ...predicate.TenantConfig) *TenantConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantConfigUpdateOne) Select(field string, fields ...string) *TenantConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TenantConfig entity.
func (_u *TenantConfigUpdateOne) Save(ctx context.Context) (*TenantConfig, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantConfigUpdateOne) SaveX(ctx context.Context) *TenantConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TenantConfigUpdateOne) sqlSave(ctx context.Context) (_node *TenantConfig, err error) {
	_spec := sqlgraph.NewUpdateSpec(tenantconfig.Table, tenantconfig.Columns, sqlgraph.NewFieldSpec(tenantconfig.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TenantConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenantconfig.FieldID)
		for _, f := range fields {
			if !tenantconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenantconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Tenant(); ok {
		_spec.SetField(tenantconfig.FieldTenant, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(tenantconfig.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &TenantConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
